// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace GrpcCustomerLoyalty
{
    public partial class MLCustomerLoyalty
    {
        /// <summary>
        /// model input class for MLCustomerLoyalty.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(12)]
            [ColumnName(@"market_segment_type")]
            public string Market_segment_type { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"repeated_guest")]
            public float Repeated_guest { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"no_of_previous_bookings_not_canceled")]
            public float No_of_previous_bookings_not_canceled { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"avg_price_per_room")]
            public float Avg_price_per_room { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"no_of_special_requests")]
            public float No_of_special_requests { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLCustomerLoyalty.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"market_segment_type")]
            public float[] Market_segment_type { get; set; }

            [ColumnName(@"repeated_guest")]
            public uint Repeated_guest { get; set; }

            [ColumnName(@"no_of_previous_bookings_not_canceled")]
            public float No_of_previous_bookings_not_canceled { get; set; }

            [ColumnName(@"avg_price_per_room")]
            public float Avg_price_per_room { get; set; }

            [ColumnName(@"no_of_special_requests")]
            public float No_of_special_requests { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLCustomerLoyalty.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("repeated_guest");
            if (labelColumn == null)
            {
                throw new Exception("repeated_guest column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
